import { useState, useEffect } from 'react';
import Button from '@mui/material/Button';
import GameOne from './Components/GameOne';
import CurrentQuestion from './Components/CurrentQuestion';

function App() {

  const [ questionApiToken, setQuestionApiToken ] = useState('');

    //this fetches a session token generated by the API and is used to make sure quesions are not repeated
  useEffect(() => {
    const fetchSessionToken = async () => {
      const url = 'https://opentdb.com/api_token.php?command=request'
      try {

        const response = await fetch(url)

        if(!response.ok){
          const errorData = await response.json();
          throw new Error(errorData.message || "Error with DataBase")
        }

        const data = await response.json();
        setQuestionApiToken(data.token)

      } catch (err) {
        console.log(err)
      }
    };
    fetchSessionToken();
  }, [])

  const [ playerOneScore, setPlayerOneScore ] = useState(0);
  const [ gameStart, setGameStart ] = useState(false);
  const [ currentQuestion, setCurrentQuestion ] = useState(null);
  const [ animate, setAnimate ] = useState(false);
  const [ gameTwo, setGameTwo ] = useState(false);
  const [ finalGame, setFinalGame ] = useState(false);

  const randomCategoryNumber = () => {
    return Math.floor(Math.random() * (32, 9 + 1)) + 9
   };

  const gameNumber = () => {
    if(finalGame) {
      return (<div>FinalGame</div>)
    } else if (gameTwo) {
      return (<div>GameTwo</div>)
    } else if (gameStart) {
      return ( 
        <GameOne 
          randomCategoryNumber={randomCategoryNumber} 
          setPlayerOneScore={setPlayerOneScore} 
          setCurrentQuestion={setCurrentQuestion}
          currentQuestion={currentQuestion}
          setGameTwo={setGameTwo}
        /> 
      )
    } else return null
  }

  //! set to 3500 
  const startGame = () => {
    setAnimate(true);
    setTimeout(() => {
      setGameStart(true);
    }, 0)
  };
  

  return (
    <div className='flex justify-center h-full bg-blue-600'>
      <section>
          <span className={`inline-block text-white text-[7em] text-shadow-lg/100 animate-slide-in-right ${animate ? 'animate-swoop-out' : ''}`}>
              J</span>
          <span className={`inline-block text-white text-[7em] text-shadow-lg/100 animate-slide-in-right-2 ${animate ? 'animate-swoop-out-2' : ''}`}>
              E</span>
          <span className={`inline-block text-white text-[7em] text-shadow-lg/100 animate-slide-in-right-3 ${animate ? 'animate-swoop-out-3' : ''}`}>
              O</span>
          <span className={`inline-block text-white text-[7em] text-shadow-lg/100 animate-slide-in-right-4 ${animate ? 'animate-swoop-out-4' : ''}`}>
              P</span>
          <span className={`inline-block text-white text-[7em] text-shadow-lg/100 animate-slide-in-right-5 ${animate ? 'animate-swoop-out-5' : ''}`}>
              A</span>
          <span className={`inline-block text-white text-[7em] text-shadow-lg/100 animate-slide-in-right-6 ${animate ? 'animate-swoop-out-6' : ''}`}>
              R</span>
          <span className={`inline-block text-white text-[7em] text-shadow-lg/100 animate-slide-in-right-7 ${animate ? 'animate-swoop-out-7' : ''}`}>
              D</span>
          <span className={`inline-block text-white text-[7em] text-shadow-lg/100 animate-slide-in-right-8 ${animate ? 'animate-swoop-out-8' : ''}`}>
              Y</span>
      </section>

      { gameNumber() }

      { currentQuestion ?
        <CurrentQuestion 
          playerOneScore={playerOneScore}
          setPlayerOneScore={setPlayerOneScore}
          currentQuestion={currentQuestion}
          setCurrentQuestion={setCurrentQuestion}
          questionApiToken={questionApiToken}
        />
        : null }

      {gameStart ? null : (
        <section className='absolute bottom-[30%] w-full flex justify-evenly'>
          <Button variant='contained' color='primary' onClick={() => startGame()}
            className={`${animate ? 'animate-slide-left-out' : '' }`}
            sx={{
              width: "15%",
            }}>One Player</Button>
          <Button variant='contained' color='primary' onClick={() => startGame()}
            className={`${animate ? 'animate-slide-left-out-2' : '' }`}
            sx={{
              width: "15%",
            }}>Two Player</Button>
          <Button variant='contained' color='primary' onClick={() => startGame()}
            className={`${animate ? 'animate-slide-left-out-3' : '' }`}
            sx={{
              width: "15%",
            }}>Three Player</Button>
        </section>
      )}

    </div>
  )
}

export default App;
